package main

import (
	"strconv"
	"strings"

	"github.com/adiom-data/commandargs/internal/plugin"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
)

func generateFile(gen *protogen.Plugin, file *protogen.File) error {
	commandMsgs := plugin.CollectCommandMessages(file)
	if len(commandMsgs) == 0 {
		return nil
	}

	filename := file.GeneratedFilenamePrefix + "_commandargs.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	g.P("// Code generated by protoc-gen-commandargs-urfave. DO NOT EDIT.")
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	g.P(`import "github.com/urfave/cli/v2"`)

	for _, msg := range commandMsgs {
		if err := plugin.ValidateMessage(msg); err != nil {
			return err
		}
	}

	for _, msg := range commandMsgs {
		ci, err := plugin.ExtractCommand(msg)
		if err != nil {
			return err
		}
		exportedName := string(msg.Desc.Name())
		flagsFuncName := exportedName + "CommandFlags"

		g.P()
		generateFlagsFunc(g, ci.Flags, flagsFuncName)
		g.P()
		generateParseFunc(g, msg, exportedName)
		g.P()
		generateNewCommand(g, ci, exportedName, flagsFuncName)
		g.P()
		generateNewApp(g, ci, exportedName, flagsFuncName)
	}

	return nil
}

func generateFlagsFunc(g *protogen.GeneratedFile, flags []plugin.FlagInfo, funcName string) {
	g.P("func ", funcName, "() []cli.Flag {")
	if len(flags) == 0 {
		g.P("	return nil")
	} else {
		g.P("	return []cli.Flag{")
		for _, f := range flags {
			generateFlag(g, f, "		")
		}
		g.P("	}")
	}
	g.P("}")
}

func generateFlag(g *protogen.GeneratedFile, f plugin.FlagInfo, indent string) {
	cliType := flagTypeToCLI(f.Type)
	g.P(indent, "&cli.", cliType, "{")
	g.P(indent, "	Name: ", quote(f.Name), ",")
	if f.Usage != "" {
		g.P(indent, "	Usage: ", quote(f.Usage), ",")
	}
	if len(f.Aliases) > 0 {
		g.P(indent, "	Aliases: []string{", joinQuoted(f.Aliases), "},")
	}
	if f.Default != "" {
		generateDefaultValue(g, f, indent+"	")
	}
	if f.Required {
		g.P(indent, "	Required: true,")
	}
	if f.Hidden {
		g.P(indent, "	Hidden: true,")
	}
	if f.Category != "" {
		g.P(indent, "	Category: ", quote(f.Category), ",")
	}
	g.P(indent, "},")
}

func generateDefaultValue(g *protogen.GeneratedFile, f plugin.FlagInfo, indent string) {
	switch f.Type {
	case plugin.FlagTypeStringList:
		elems := plugin.SplitDefault(f.Default)
		g.P(indent, "Value: cli.NewStringSlice(", joinQuoted(elems), "),")
	case plugin.FlagTypeIntList:
		g.P(indent, "Value: cli.NewIntSlice(", f.Default, "),")
	case plugin.FlagTypeInt64List:
		g.P(indent, "Value: cli.NewInt64Slice(", f.Default, "),")
	case plugin.FlagTypeDuration:
		timeParseDuration := protogen.GoIdent{GoName: "ParseDuration", GoImportPath: "time"}
		timeDuration := protogen.GoIdent{GoName: "Duration", GoImportPath: "time"}
		g.P(indent, "Value: func() ", timeDuration, " { d, _ := ", timeParseDuration, "(", quote(f.Default), "); return d }(),")
	case plugin.FlagTypeBool, plugin.FlagTypeInt, plugin.FlagTypeInt64, plugin.FlagTypeFloat64:
		g.P(indent, "Value: ", f.Default, ",")
	default:
		g.P(indent, "Value: ", quote(f.Default), ",")
	}
}

func generateParseFunc(g *protogen.GeneratedFile, msg *protogen.Message, exportedName string) {
	g.P("func Parse", exportedName, "(c *cli.Context) (*", msg.GoIdent, ", error) {")
	g.P("	cfg := &", msg.GoIdent, "{}")
	generateParseAssignments(g, msg, "cfg")
	g.P("	return cfg, nil")
	g.P("}")
}

func generateParseAssignments(g *protogen.GeneratedFile, msg *protogen.Message, receiver string) {
	for _, field := range msg.Fields {
		wkt, isWKT := plugin.GetWellKnownType(field)
		if field.Message != nil && !isWKT {
			subReceiver := receiver + "." + field.GoName
			g.P("	", subReceiver, " = &", field.Message.GoIdent, "{}")
			generateParseAssignments(g, field.Message, subReceiver)
		} else if isWKT && field.Desc.IsList() {
			generateRepeatedWKTAssignment(g, field, receiver)
		} else if isWKT {
			generateWKTAssignment(g, field, wkt, receiver)
		} else {
			generateScalarAssignment(g, field, receiver)
		}
	}
}

func generateWKTAssignment(g *protogen.GeneratedFile, field *protogen.Field, wkt plugin.WellKnownTypeInfo, receiver string) {
	flagName := plugin.FlagNameForField(field)
	assign := receiver + "." + field.GoName
	fullName := string(field.Message.Desc.FullName())

	switch fullName {
	case "google.protobuf.Duration":
		wrapIdent := protogen.GoIdent{GoName: "New", GoImportPath: "google.golang.org/protobuf/types/known/durationpb"}
		g.P("	", assign, " = ", wrapIdent, "(c.Duration(", quote(flagName), "))")
	case "google.protobuf.Timestamp":
		timeParseIdent := protogen.GoIdent{GoName: "Parse", GoImportPath: "time"}
		rfc3339Ident := protogen.GoIdent{GoName: "RFC3339", GoImportPath: "time"}
		tsNewIdent := protogen.GoIdent{GoName: "New", GoImportPath: "google.golang.org/protobuf/types/known/timestamppb"}
		fmtErrorf := protogen.GoIdent{GoName: "Errorf", GoImportPath: "fmt"}
		g.P("	if v := c.String(", quote(flagName), "); v != \"\" {")
		g.P("		t, err := ", timeParseIdent, "(", rfc3339Ident, ", v)")
		g.P("		if err != nil {")
		g.P(`			return nil, `, fmtErrorf, `("invalid timestamp for flag `, flagName, `: %w", err)`)
		g.P("		}")
		g.P("		", assign, " = ", tsNewIdent, "(t)")
		g.P("	}")
	default:
		wrapFunc := wrapperFuncs[fullName]
		wrapIdent := protogen.GoIdent{GoName: wrapFunc.funcName, GoImportPath: "google.golang.org/protobuf/types/known/wrapperspb"}
		getter := wrapFunc.getter + "(" + quote(flagName) + ")"
		if wrapFunc.castFunc != "" {
			g.P("	", assign, " = ", wrapIdent, "(", wrapFunc.castFunc, "(", getter, "))")
		} else {
			g.P("	", assign, " = ", wrapIdent, "(", getter, ")")
		}
	}
}

func generateRepeatedWKTAssignment(g *protogen.GeneratedFile, field *protogen.Field, receiver string) {
	flagName := plugin.FlagNameForField(field)
	assign := receiver + "." + field.GoName
	fullName := string(field.Message.Desc.FullName())
	fmtErrorf := protogen.GoIdent{GoName: "Errorf", GoImportPath: "fmt"}

	g.P("	for _, v := range c.StringSlice(", quote(flagName), ") {")

	switch fullName {
	case "google.protobuf.Duration":
		parseDur := protogen.GoIdent{GoName: "ParseDuration", GoImportPath: "time"}
		wrapNew := protogen.GoIdent{GoName: "New", GoImportPath: "google.golang.org/protobuf/types/known/durationpb"}
		g.P("		d, err := ", parseDur, "(v)")
		g.P("		if err != nil {")
		g.P(`			return nil, `, fmtErrorf, `("invalid duration for flag `, flagName, `: %w", err)`)
		g.P("		}")
		g.P("		", assign, " = append(", assign, ", ", wrapNew, "(d))")
	case "google.protobuf.Timestamp":
		timeParse := protogen.GoIdent{GoName: "Parse", GoImportPath: "time"}
		rfc3339 := protogen.GoIdent{GoName: "RFC3339", GoImportPath: "time"}
		tsNew := protogen.GoIdent{GoName: "New", GoImportPath: "google.golang.org/protobuf/types/known/timestamppb"}
		g.P("		t, err := ", timeParse, "(", rfc3339, ", v)")
		g.P("		if err != nil {")
		g.P(`			return nil, `, fmtErrorf, `("invalid timestamp for flag `, flagName, `: %w", err)`)
		g.P("		}")
		g.P("		", assign, " = append(", assign, ", ", tsNew, "(t))")
	case "google.protobuf.StringValue":
		wrap := protogen.GoIdent{GoName: "String", GoImportPath: "google.golang.org/protobuf/types/known/wrapperspb"}
		g.P("		", assign, " = append(", assign, ", ", wrap, "(v))")
	case "google.protobuf.BoolValue":
		parseBool := protogen.GoIdent{GoName: "ParseBool", GoImportPath: "strconv"}
		wrap := protogen.GoIdent{GoName: "Bool", GoImportPath: "google.golang.org/protobuf/types/known/wrapperspb"}
		g.P("		b, err := ", parseBool, "(v)")
		g.P("		if err != nil {")
		g.P(`			return nil, `, fmtErrorf, `("invalid bool for flag `, flagName, `: %w", err)`)
		g.P("		}")
		g.P("		", assign, " = append(", assign, ", ", wrap, "(b))")
	case "google.protobuf.Int32Value":
		parseInt := protogen.GoIdent{GoName: "ParseInt", GoImportPath: "strconv"}
		wrap := protogen.GoIdent{GoName: "Int32", GoImportPath: "google.golang.org/protobuf/types/known/wrapperspb"}
		g.P("		n, err := ", parseInt, "(v, 10, 32)")
		g.P("		if err != nil {")
		g.P(`			return nil, `, fmtErrorf, `("invalid int32 for flag `, flagName, `: %w", err)`)
		g.P("		}")
		g.P("		", assign, " = append(", assign, ", ", wrap, "(int32(n)))")
	case "google.protobuf.Int64Value":
		parseInt := protogen.GoIdent{GoName: "ParseInt", GoImportPath: "strconv"}
		wrap := protogen.GoIdent{GoName: "Int64", GoImportPath: "google.golang.org/protobuf/types/known/wrapperspb"}
		g.P("		n, err := ", parseInt, "(v, 10, 64)")
		g.P("		if err != nil {")
		g.P(`			return nil, `, fmtErrorf, `("invalid int64 for flag `, flagName, `: %w", err)`)
		g.P("		}")
		g.P("		", assign, " = append(", assign, ", ", wrap, "(n))")
	case "google.protobuf.FloatValue":
		parseFloat := protogen.GoIdent{GoName: "ParseFloat", GoImportPath: "strconv"}
		wrap := protogen.GoIdent{GoName: "Float", GoImportPath: "google.golang.org/protobuf/types/known/wrapperspb"}
		g.P("		f, err := ", parseFloat, "(v, 32)")
		g.P("		if err != nil {")
		g.P(`			return nil, `, fmtErrorf, `("invalid float for flag `, flagName, `: %w", err)`)
		g.P("		}")
		g.P("		", assign, " = append(", assign, ", ", wrap, "(float32(f)))")
	case "google.protobuf.DoubleValue":
		parseFloat := protogen.GoIdent{GoName: "ParseFloat", GoImportPath: "strconv"}
		wrap := protogen.GoIdent{GoName: "Double", GoImportPath: "google.golang.org/protobuf/types/known/wrapperspb"}
		g.P("		f, err := ", parseFloat, "(v, 64)")
		g.P("		if err != nil {")
		g.P(`			return nil, `, fmtErrorf, `("invalid double for flag `, flagName, `: %w", err)`)
		g.P("		}")
		g.P("		", assign, " = append(", assign, ", ", wrap, "(f))")
	}

	g.P("	}")
}

type wrapperFunc struct {
	funcName string
	getter   string
	castFunc string
}

var wrapperFuncs = map[string]wrapperFunc{
	"google.protobuf.StringValue": {funcName: "String", getter: "c.String", castFunc: ""},
	"google.protobuf.BoolValue":   {funcName: "Bool", getter: "c.Bool", castFunc: ""},
	"google.protobuf.Int32Value":  {funcName: "Int32", getter: "c.Int", castFunc: "int32"},
	"google.protobuf.Int64Value":  {funcName: "Int64", getter: "c.Int64", castFunc: ""},

	"google.protobuf.FloatValue":  {funcName: "Float", getter: "c.Float64", castFunc: "float32"},
	"google.protobuf.DoubleValue": {funcName: "Double", getter: "c.Float64", castFunc: ""},
}

func generateScalarAssignment(g *protogen.GeneratedFile, field *protogen.Field, receiver string) {
	flagName := plugin.FlagNameForField(field)
	assign := receiver + "." + field.GoName
	if field.Desc.IsList() {
		if needsSliceCast(field.Desc) {
			getter := listGetter(field.Desc, flagName)
			g.P("	{")
			g.P("		raw := ", getter)
			g.P("		conv := make([]int32, len(raw))")
			g.P("		for i, v := range raw {")
			g.P("			conv[i] = int32(v)")
			g.P("		}")
			g.P("		", assign, " = conv")
			g.P("	}")
		} else {
			g.P("	", assign, " = ", listGetter(field.Desc, flagName))
		}
	} else {
		getter := scalarGetter(field.Desc, flagName)
		if needsCast(field.Desc) {
			g.P("	", assign, " = ", castExpr(field.Desc, getter))
		} else {
			g.P("	", assign, " = ", getter)
		}
	}
	opts := plugin.GetFlagOptions(field)
	if opts != nil && len(opts.GetAllowedValues()) > 0 {
		generateAllowedValuesCheck(g, assign, flagName, opts.GetAllowedValues(), field.Desc.IsList())
	}
}

func generateAllowedValuesCheck(g *protogen.GeneratedFile, assignExpr string, flagName string, allowedValues []string, isList bool) {
	fmtSprint := protogen.GoIdent{GoName: "Sprint", GoImportPath: "fmt"}
	fmtErrorf := protogen.GoIdent{GoName: "Errorf", GoImportPath: "fmt"}
	if isList {
		g.P("	{")
		g.P("		allowed := map[string]bool{")
		for _, v := range allowedValues {
			g.P("			", quote(v), ": true,")
		}
		g.P("		}")
		g.P("		for _, v := range ", assignExpr, " {")
		g.P("			if !allowed[", fmtSprint, "(v)] {")
		g.P(`				return nil, `, fmtErrorf, `("invalid value %q for flag `, flagName, `, allowed: %v", v, allowed)`)
		g.P("			}")
		g.P("		}")
		g.P("	}")
	} else {
		g.P("	if c.IsSet(", quote(flagName), ") {")
		g.P("		allowed := []string{", joinQuoted(allowedValues), "}")
		g.P("		valid := false")
		g.P("		for _, a := range allowed {")
		g.P("			if ", fmtSprint, "(", assignExpr, ") == a {")
		g.P("				valid = true")
		g.P("				break")
		g.P("			}")
		g.P("		}")
		g.P("		if !valid {")
		g.P(`			return nil, `, fmtErrorf, `("invalid value %q for flag `, flagName, `, allowed: %v", `, fmtSprint, `(`, assignExpr, `), allowed)`)
		g.P("		}")
		g.P("	}")
	}
}

func generateNewCommand(g *protogen.GeneratedFile, ci plugin.CommandInfo, exportedName string, flagsFuncName string) {
	g.P("func New", exportedName, "Command(action cli.ActionFunc, subcommands ...*cli.Command) *cli.Command {")
	g.P("	return &cli.Command{")
	g.P("		Name: ", quote(ci.Name), ",")
	if ci.Description != "" {
		g.P("		Description: ", quote(ci.Description), ",")
	}
	if ci.Usage != "" {
		g.P("		Usage: ", quote(ci.Usage), ",")
	}
	if len(ci.Aliases) > 0 {
		g.P("		Aliases: []string{", joinQuoted(ci.Aliases), "},")
	}
	if ci.Hidden {
		g.P("		Hidden: true,")
	}
	if ci.Category != "" {
		g.P("		Category: ", quote(ci.Category), ",")
	}
	g.P("		Flags:       ", flagsFuncName, "(),")
	g.P("		Subcommands: subcommands,")
	g.P("		Action:      action,")
	g.P("	}")
	g.P("}")
}

func generateNewApp(g *protogen.GeneratedFile, ci plugin.CommandInfo, exportedName string, flagsFuncName string) {
	g.P("func New", exportedName, "App(action cli.ActionFunc, subcommands ...*cli.Command) *cli.App {")
	g.P("	return &cli.App{")
	g.P("		Name: ", quote(ci.Name), ",")
	if ci.Description != "" {
		g.P("		Description: ", quote(ci.Description), ",")
	}
	if ci.Usage != "" {
		g.P("		Usage: ", quote(ci.Usage), ",")
	}
	if ci.Hidden {
		g.P("		HideHelp: true,")
	}
	g.P("		Flags:    ", flagsFuncName, "(),")
	g.P("		Commands: subcommands,")
	g.P("		Action:   action,")
	g.P("	}")
	g.P("}")
}

func flagTypeToCLI(ft plugin.FlagType) string {
	switch ft {
	case plugin.FlagTypeBool:
		return "BoolFlag"
	case plugin.FlagTypeInt:
		return "IntFlag"
	case plugin.FlagTypeInt64:
		return "Int64Flag"
	case plugin.FlagTypeFloat64:
		return "Float64Flag"
	case plugin.FlagTypeDuration:
		return "DurationFlag"
	case plugin.FlagTypeStringList:
		return "StringSliceFlag"
	case plugin.FlagTypeIntList:
		return "IntSliceFlag"
	case plugin.FlagTypeInt64List:
		return "Int64SliceFlag"
	default:
		return "StringFlag"
	}
}

func scalarGetter(fd protoreflect.FieldDescriptor, name string) string {
	q := quote(name)
	switch fd.Kind() {
	case protoreflect.BoolKind:
		return "c.Bool(" + q + ")"
	case protoreflect.Int32Kind, protoreflect.Sint32Kind:
		return "c.Int(" + q + ")"
	case protoreflect.Int64Kind, protoreflect.Sint64Kind:
		return "c.Int64(" + q + ")"
	case protoreflect.FloatKind, protoreflect.DoubleKind:
		return "c.Float64(" + q + ")"
	default:
		return "c.String(" + q + ")"
	}
}

func listGetter(fd protoreflect.FieldDescriptor, name string) string {
	q := quote(name)
	switch fd.Kind() {
	case protoreflect.StringKind:
		return "c.StringSlice(" + q + ")"
	case protoreflect.Int32Kind, protoreflect.Sint32Kind:
		return "c.IntSlice(" + q + ")"
	case protoreflect.Int64Kind, protoreflect.Sint64Kind:
		return "c.Int64Slice(" + q + ")"
	default:
		return "c.StringSlice(" + q + ")"
	}
}

func needsCast(fd protoreflect.FieldDescriptor) bool {
	switch fd.Kind() {
	case protoreflect.Int32Kind, protoreflect.Sint32Kind:
		return true
	case protoreflect.FloatKind:
		return true
	}
	return false
}

func castExpr(fd protoreflect.FieldDescriptor, getter string) string {
	switch fd.Kind() {
	case protoreflect.Int32Kind, protoreflect.Sint32Kind:
		return "int32(" + getter + ")"
	case protoreflect.FloatKind:
		return "float32(" + getter + ")"
	}
	return getter
}

func needsSliceCast(fd protoreflect.FieldDescriptor) bool {
	switch fd.Kind() {
	case protoreflect.Int32Kind, protoreflect.Sint32Kind:
		return true
	}
	return false
}

func quote(s string) string {
	return strconv.Quote(s)
}

func joinQuoted(ss []string) string {
	var parts []string
	for _, s := range ss {
		parts = append(parts, quote(s))
	}
	return strings.Join(parts, ", ")
}
