package main

import (
	"fmt"
	"strings"

	"github.com/adiom-data/commandargs/internal/plugin"
	"google.golang.org/protobuf/compiler/protogen"
)

func generateFile(gen *protogen.Plugin, file *protogen.File) error {
	commandMsgs := plugin.CollectCommandMessages(file)
	if len(commandMsgs) == 0 {
		return nil
	}

	for _, msg := range commandMsgs {
		if err := plugin.ValidateMessage(msg); err != nil {
			return err
		}
	}

	filename := file.GeneratedFilenamePrefix + "_commandargs.ts"
	g := gen.NewGeneratedFile(filename, "")

	g.P("// Code generated by protoc-gen-commandargs-ts. DO NOT EDIT.")
	g.P()
	g.P("// Flag type descriptors for UI rendering.")
	g.P(`export type FlagType = "string" | "bool" | "int" | "int64" | "float64" | "duration" | "timestamp" | "string_list" | "int_list" | "int64_list";`)
	g.P()
	g.P("export interface FlagDescriptor {")
	g.P("  name: string;")
	g.P("  type: FlagType;")
	g.P("  usage?: string;")
	g.P("  default?: string | number | boolean;")
	g.P("  required?: boolean;")
	g.P("  hidden?: boolean;")
	g.P("  category?: string;")
	g.P("  aliases?: string[];")
	g.P("  allowedValues?: string[];")
	g.P("}")
	g.P()
	g.P("export interface CommandDescriptor {")
	g.P("  name: string;")
	g.P("  description?: string;")
	g.P("  usage?: string;")
	g.P("  hidden?: boolean;")
	g.P("  category?: string;")
	g.P("  aliases?: string[];")
	g.P("  flags: FlagDescriptor[];")
	g.P("}")

	for _, msg := range commandMsgs {
		ci, err := plugin.ExtractCommand(msg)
		if err != nil {
			return err
		}
		exportedName := string(msg.Desc.Name())

		g.P()
		generateDescriptor(g, ci, exportedName)
		g.P()
		generateFormState(g, ci, exportedName)
		g.P()
		generateDefaults(g, ci, exportedName)
		g.P()
		generateBuilder(g, msg, ci, exportedName)
	}

	return nil
}

func generateDescriptor(g *protogen.GeneratedFile, ci plugin.CommandInfo, exportedName string) {
	g.P("export const ", exportedName, "Command: CommandDescriptor = {")
	g.P(`  name: "`, ci.Name, `",`)
	if ci.Description != "" {
		g.P(`  description: "`, escapeTS(ci.Description), `",`)
	}
	if ci.Usage != "" {
		g.P(`  usage: "`, escapeTS(ci.Usage), `",`)
	}
	if ci.Hidden {
		g.P("  hidden: true,")
	}
	if ci.Category != "" {
		g.P(`  category: "`, escapeTS(ci.Category), `",`)
	}
	if len(ci.Aliases) > 0 {
		g.P("  aliases: [", joinTSStrings(ci.Aliases), "],")
	}
	g.P("  flags: [")
	for _, f := range ci.Flags {
		g.P("    {")
		g.P(`      name: "`, f.Name, `",`)
		g.P(`      type: "`, string(f.Type), `",`)
		if f.Usage != "" {
			g.P(`      usage: "`, escapeTS(f.Usage), `",`)
		}
		if f.Default != "" {
			g.P("      default: ", tsDefaultValue(f), ",")
		}
		if f.Required {
			g.P("      required: true,")
		}
		if f.Hidden {
			g.P("      hidden: true,")
		}
		if f.Category != "" {
			g.P(`      category: "`, escapeTS(f.Category), `",`)
		}
		if len(f.Aliases) > 0 {
			g.P("      aliases: [", joinTSStrings(f.Aliases), "],")
		}
		if len(f.AllowedValues) > 0 {
			g.P("      allowedValues: [", joinTSStrings(f.AllowedValues), "],")
		}
		g.P("    },")
	}
	g.P("  ],")
	g.P("};")
}

func generateFormState(g *protogen.GeneratedFile, ci plugin.CommandInfo, exportedName string) {
	g.P("export interface ", exportedName, "FormState {")
	for _, f := range ci.Flags {
		g.P(`  "`, f.Name, `": `, tsFormType(f.Type), ";")
	}
	g.P("}")
}

func generateDefaults(g *protogen.GeneratedFile, ci plugin.CommandInfo, exportedName string) {
	g.P("export const ", exportedName, "Defaults: ", exportedName, "FormState = {")
	for _, f := range ci.Flags {
		g.P(`  "`, f.Name, `": `, tsDefaultOrZero(f), ",")
	}
	g.P("};")
}

func generateBuilder(g *protogen.GeneratedFile, msg *protogen.Message, ci plugin.CommandInfo, exportedName string) {
	paramName := "state"
	if len(ci.Flags) == 0 {
		paramName = "_state"
	}
	g.P("export function build", exportedName, "Proto(", paramName, ": ", exportedName, "FormState): Record<string, unknown> {")
	g.P("  return {")
	generateBuilderFields(g, msg, "state", "    ")
	g.P("  };")
	g.P("}")
}

func generateBuilderFields(g *protogen.GeneratedFile, msg *protogen.Message, stateVar string, indent string) {
	for _, field := range msg.Fields {
		_, isWKT := plugin.GetWellKnownType(field)
		if field.Message != nil && !isWKT {
			g.P(indent, camelCase(string(field.Desc.Name())), ": {")
			generateBuilderFields(g, field.Message, stateVar, indent+"  ")
			g.P(indent, "},")
		} else {
			flagName := plugin.FlagNameForField(field)
			jsKey := camelCase(string(field.Desc.Name()))
			fullName := ""
			if isWKT {
				fullName = string(field.Message.Desc.FullName())
			}
			g.P(indent, jsKey, ": ", builderExpr(flagName, fullName, field, stateVar), ",")
		}
	}
}

func builderExpr(flagName string, wktFullName string, field *protogen.Field, stateVar string) string {
	accessor := stateVar + `["` + flagName + `"]`
	if field.Desc.IsList() {
		if wktFullName == "" {
			return accessor
		}
		mapExpr := repeatedWKTMapExpr(wktFullName)
		if mapExpr == "" {
			return accessor
		}
		return accessor + ".map(" + mapExpr + ")"
	}
	switch wktFullName {
	case "google.protobuf.Duration":
		return accessor
	case "google.protobuf.Timestamp":
		return accessor + ` ? { seconds: Math.floor(new Date(` + accessor + `).getTime() / 1000) } : undefined`
	case "google.protobuf.StringValue", "google.protobuf.BoolValue",
		"google.protobuf.Int32Value", "google.protobuf.Int64Value",
		"google.protobuf.FloatValue", "google.protobuf.DoubleValue":
		return "{ value: " + accessor + " }"
	default:
		return accessor
	}
}

func repeatedWKTMapExpr(wktFullName string) string {
	switch wktFullName {
	case "google.protobuf.Duration":
		return ""
	case "google.protobuf.Timestamp":
		return "(v: string) => ({ seconds: Math.floor(new Date(v).getTime() / 1000) })"
	case "google.protobuf.StringValue":
		return "(v: string) => ({ value: v })"
	case "google.protobuf.BoolValue":
		return "(v: string) => ({ value: v === \"true\" })"
	case "google.protobuf.Int32Value", "google.protobuf.Int64Value":
		return "(v: string) => ({ value: Number(v) })"
	case "google.protobuf.FloatValue", "google.protobuf.DoubleValue":
		return "(v: string) => ({ value: Number(v) })"
	default:
		return ""
	}
}

func tsFormType(ft plugin.FlagType) string {
	switch ft {
	case plugin.FlagTypeBool:
		return "boolean"
	case plugin.FlagTypeInt, plugin.FlagTypeInt64, plugin.FlagTypeFloat64:
		return "number"
	case plugin.FlagTypeDuration, plugin.FlagTypeTimestamp, plugin.FlagTypeString:
		return "string"
	case plugin.FlagTypeStringList:
		return "string[]"
	case plugin.FlagTypeIntList, plugin.FlagTypeInt64List:
		return "number[]"
	default:
		return "string"
	}
}

func tsDefaultValue(f plugin.FlagInfo) string {
	switch f.Type {
	case plugin.FlagTypeStringList:
		elems := plugin.SplitDefault(f.Default)
		return "[" + joinTSStrings(elems) + "]"
	case plugin.FlagTypeIntList, plugin.FlagTypeInt64List:
		return "[" + f.Default + "]"
	case plugin.FlagTypeBool:
		return f.Default
	case plugin.FlagTypeInt, plugin.FlagTypeInt64, plugin.FlagTypeFloat64:
		return f.Default
	default:
		return `"` + escapeTS(f.Default) + `"`
	}
}

func tsDefaultOrZero(f plugin.FlagInfo) string {
	if f.Default != "" {
		return tsDefaultValue(f)
	}
	switch f.Type {
	case plugin.FlagTypeBool:
		return "false"
	case plugin.FlagTypeInt, plugin.FlagTypeInt64, plugin.FlagTypeFloat64:
		return "0"
	case plugin.FlagTypeStringList:
		return "[]"
	case plugin.FlagTypeIntList, plugin.FlagTypeInt64List:
		return "[]"
	default:
		return `""`
	}
}

func camelCase(s string) string {
	parts := strings.Split(s, "_")
	for i := 1; i < len(parts); i++ {
		if len(parts[i]) > 0 {
			parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
		}
	}
	return strings.Join(parts, "")
}

func escapeTS(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	return s
}

func joinTSStrings(ss []string) string {
	var parts []string
	for _, s := range ss {
		parts = append(parts, fmt.Sprintf(`"%s"`, escapeTS(s)))
	}
	return strings.Join(parts, ", ")
}
